### ISSUE TITLE
Unmet requirements: docker.server.osType contains linux

### ISSUE THREAD

**Issue by ChrisScottThomas** [JetBrains/teamcity-kubernetes-plugin#45]
Hey,

We're having issues with the plugin, where it's telling us we have unmet requirements.  yet as far as we can tell the requirements **are** being met.

Shows the image doesn't meet requirements:
![unmet1](https://user-images.githubusercontent.com/47419381/55226385-ce8dde80-520c-11e9-8c03-87be0560107c.PNG)

Yet, in the agent details you can clearly see the OS is 
`Operating system: Linux, version 3.10.0-957.el7.x86_64`

![unmet2](https://user-images.githubusercontent.com/47419381/55226391-d2216580-520c-11e9-9164-71ffcf6916ef.PNG)

Nothing in the documentation eludes to this issue.  We're using `image: jetbrains/teamcity-agent:latest` in our deployment. and using that to template the agent as in the docs.

Are we doing something wrong?

**Comment by ChrisScottThomas** [comment]
I did manage to get an agent working with a custom pod template:

```
apiVersion: v1
kind: pod
metadata:
  name: agent-pod
  namespace: teamcity
  labels:
    app: agent-pod
spec:
  containers:
  - name: agent-pod
    image: jetbrains/teamcity-agent
    imagePullPolicy: IfNotPresent
    securityContext:
      allowPrivilegeEscalation: true
    env:
    - name: DOCKER_IN_DOCKER
      value: "start"
    dnsPolicy: ClusterFirst
```

But I'm still getting the same results.  I can only assume it's pulling the underlying OS kernel version which is Ubuntu 16.04 LTS, not the containers Bionic kernel on 4.10+.
