### ISSUE TITLE
pod tolerations in kubernetes v1.6.7 not working

### ISSUE THREAD

**Issue by lkirill** [JetBrains/teamcity-kubernetes-plugin#8]
if in deployment set toleration:
```
...
    spec:
      tolerations: 
      - key: "dedicated"
        operator: "Equal"
        value: "teamcity"
        effect: "NoSchedule"
...
```
pod with teamcity-agent, created by plugin from this deployment doesn't have this toleration:
```
kubectl describe pod b7036e2b-7921-4308-ac28-423bf1d78147 | grep Tolerations
Tolerations:	<none>
```

**Comment by lkirill** [comment]
Also in kubernetes 1.6.7 not working nodeAffinity:
```
...
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "teamcity-agents"
                operator: "In"
                values: ["true"]
...
```
